---
# File: roles/install-wordpress/tasks/main.yml
# Purpose: Install and configure WordPress on a target droplet.

- name: Copy DigitalOcean Root CA Certificate to /etc/pki/ca-trust/source/anchors/
  copy:
    src: '../files/ca-certificate.crt'
    dest: '/etc/pki/ca-trust/source/anchors/'
  register: do_cert_added

- name: Install DigitalOcean Root CA Certificate
  shell: update-ca-trust
  when: do_cert_added.changed

- name: Check if WordPress has already been installed
  stat:
    path: '{{ wp_install_directory }}/wp-config.php'
  register: is_wp_installed

- name: Download and extract WordPress package
  unarchive:
    src: '{{ wp_download_url }}'
    dest: '{{ wp_install_directory }}'
    remote_src: yes
    extra_opts: [--strip-components=1]
  when: not is_wp_installed.stat.exists

- name: Generate WordPress salts for wp-admin.php
  get_url:
    url: '{{ wp_salt_gen_url }}'
    dest: '/tmp/wp_salts'
  when: not is_wp_installed.stat.exists

- name: Create variable from salts downloaded
  shell: 'cat /tmp/wp_salts'
  register: wp_salts
  when: not is_wp_installed.stat.exists

- name: Ensure /tmp/wp_salts is not present
  file:
    path: '/tmp/wp_salts'
    state: absent

- name: Create wp-config.php
  template:
    src: '../templates/wp-config.php.j2'
    dest: '{{ wp_install_directory }}/wp-config.php'
  when: not is_wp_installed.stat.exists
