---
# File: role/database-server/tasks/create.yml
# Purpose: Create and configures a DigitalOcean managed database server.

- name: 'Ensure database server exists and is configured'
  command: 'python3 /tmp/digital_ocean_database.py -a create -t {{ do_api_token }} -s {{ dbs_name }} -r {{ dbs_region }} -d {{ database_name }} -u {{ database_user }} -i {{ ip_address }} -o /tmp/db_configuration.json'
