---
# File: playbooks/configure-infra.yml
# Purpose: Configures target droplet to run as a web server.

- hosts: webserver
  gather_facts: true
  vars:
    - db_server_action: 'create'
  vars_files:
    - ../defaults/secrets.yml
    - ../defaults/common_vars.yml

  roles:
    - ../roles/configure-mounts
    - ../roles/centos-base
    - ../roles/create-swap
    - ../roles/configure-apache
    - ../roles/database-server
    - ../roles/install-wordpress
