---
# File: playbooks/destroy-infra.yml
# Purpose: Destroys ALL infrastructure associated to website.

- hosts: localhost
  gather_facts: true
  vars_files:
    - ../defaults/secrets.yml
    - ../defaults/common_vars.yml

  roles:
    - ../roles/destroy-droplet
    - ../roles/destroy-volume
